# Generated by Django 3.2.9 on 2021-11-25 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='consumer_id',
            new_name='consumer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='item_id',
            new_name='item',
        ),
    ]
