# Generated by Django 3.2.9 on 2021-11-28 01:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='account',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator]),
        ),
    ]
