# Generated by Django 3.2.9 on 2021-11-28 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_consumer_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='item_id',
            new_name='item',
        ),
    ]
