# Generated by Django 3.2.9 on 2021-11-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_item_id_image_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media/%Y/%m/%d/'),
        ),
    ]
