# Generated by Django 3.2.9 on 2021-11-29 03:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='images',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
