# Generated by Django 3.2.9 on 2021-11-29 03:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_images_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator]),
        ),
    ]
