# Generated by Django 3.2.9 on 2021-12-07 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20211130_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.BinaryField(blank=True, validators=[django.core.validators.FileExtensionValidator]),
        ),
    ]
